require("mason").setup({})
require("mason-lspconfig").setup({
	ensure_installed = {
		"astro",
		"cssls",
		"css_variables",
		"cssmodules_ls",
		"docker_compose_language_service",
		"dockerls",
		"eslint",
		"html",
		"intelephense",
		"lua_ls",
		"marksman",
		"svelte",
		"tailwindcss",
		"unocss",
		"vtsls",
		"volar",
	},
})
